const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const { Pool } = require('pg');
const cors = require('cors');
const path = require('path');
const multer = require('multer');
const { v2: cloudinary } = require('cloudinary');
require('dotenv').config();

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: '*',
    methods: ['GET', 'POST'],
    credentials: true
  },
  pingTimeout: 10000,
  pingInterval: 25000
});

app.use(cors());
app.use(express.json({ limit: '10mb' }));

const publicPath = path.join(__dirname, '../dist');
app.use(express.static(publicPath));

// --- PostgreSQL Setup ---
const DATABASE_URL = process.env.DATABASE_URL || process.env.POSTGRES_URI;
let pool = null;
let isPgConnected = false;

if (DATABASE_URL) {
  const isSSL = DATABASE_URL.includes('sslmode=require') || process.env.NODE_ENV === 'production';
  pool = new Pool({
    connectionString: DATABASE_URL,
    ssl: isSSL ? { rejectUnauthorized: false } : false
  });

  // Verify connection & create schema if not exists
  pool.query('SELECT NOW()')
    .then(async () => {
      isPgConnected = true;
      console.log('✅ GOAT PostgreSQL Database Connected');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS rooms (
          room_id VARCHAR(255) PRIMARY KEY,
          code TEXT NOT NULL DEFAULT '// Ready for collaboration...',
          language VARCHAR(50) DEFAULT 'javascript',
          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS snapshots (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          room_id VARCHAR(255) NOT NULL REFERENCES rooms(room_id) ON DELETE CASCADE,
          code TEXT NOT NULL,
          language VARCHAR(50) DEFAULT 'javascript',
          timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
      `);
      await pool.query(`
        CREATE INDEX IF NOT EXISTS idx_snapshots_room_id_timestamp 
        ON snapshots (room_id, timestamp ASC);
      `);
      console.log('✅ Schema tables and indexes initialized');
    })
    .catch(err => {
      isPgConnected = false;
      console.error('⚠️ PostgreSQL connection warning (In-Memory Room Store Active):', err.message);
    });
} else {
  console.log('ℹ️ DATABASE_URL not set. Running in-memory database store.');
}

// --- Cloudinary & Multer Setup ---
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

// Upload Endpoint for Images/Files
app.post('/api/upload', upload.single('file'), async (req, res) => {
  try {
    if (req.file) {
      const uploadStream = cloudinary.uploader.upload_stream(
        { folder: 'goat_editor' },
        (error, result) => {
          if (error) {
            console.error('Cloudinary stream upload error:', error);
            return res.status(500).json({ error: error.message || 'Upload failed' });
          }
          return res.json({ success: true, url: result.secure_url, public_id: result.public_id });
        }
      );
      uploadStream.end(req.file.buffer);
    } else if (req.body && req.body.image) {
      const result = await cloudinary.uploader.upload(req.body.image, { folder: 'goat_editor' });
      return res.json({ success: true, url: result.secure_url, public_id: result.public_id });
    } else {
      return res.status(400).json({ error: 'No file or image payload provided' });
    }
  } catch (err) {
    console.error('Upload Endpoint Error:', err);
    return res.status(500).json({ error: err.message || 'Internal server error during upload' });
  }
});

// --- In-Memory Fallback ---
const inMemoryRooms = new Map();

async function getOrCreateRoom(roomId, username) {
  if (isPgConnected && pool) {
    try {
      const roomRes = await pool.query('SELECT room_id, code, language FROM rooms WHERE room_id = $1', [roomId]);
      let code = `// Established secure link for ${username}\n// Room ${roomId}\nconsole.log("Kernel online.");`;
      let language = 'javascript';

      if (roomRes.rows.length > 0) {
        code = roomRes.rows[0].code;
        language = roomRes.rows[0].language;
      } else {
        await pool.query(
          'INSERT INTO rooms (room_id, code, language, updated_at) VALUES ($1, $2, $3, NOW()) ON CONFLICT (room_id) DO NOTHING',
          [roomId, code, language]
        );
      }

      const snapRes = await pool.query(
        'SELECT code, language, timestamp FROM snapshots WHERE room_id = $1 ORDER BY timestamp ASC',
        [roomId]
      );

      return {
        code,
        language,
        snapshots: snapRes.rows || []
      };
    } catch (err) {
      console.warn('⚠️ Postgres query failed, falling back to memory:', err.message);
    }
  }

  if (!inMemoryRooms.has(roomId)) {
    inMemoryRooms.set(roomId, {
      roomId,
      code: `// Established secure link for ${username}\n// Room ${roomId}\nconsole.log("Kernel online.");`,
      language: 'javascript',
      snapshots: []
    });
  }
  return inMemoryRooms.get(roomId);
}

const userMap = new Map(); // socketId -> { username, roomId, color, id }

io.on('connection', (socket) => {
  console.log('📡 Node joined:', socket.id);

  socket.on('join-room', async ({ roomId, username, color }) => {
    socket.join(roomId);
    userMap.set(socket.id, { username, roomId, color, id: socket.id });

    try {
      const room = await getOrCreateRoom(roomId, username);

      // Sync state to the requester only
      socket.emit('sync-state', {
        code: room.code,
        language: room.language,
        snapshots: room.snapshots || [],
        users: Array.from(userMap.values()).filter(u => u.roomId === roomId)
      });

      // Announce arrival to others
      socket.to(roomId).emit('user-joined', { username, color, id: socket.id });
    } catch (error) {
      console.error('Critical Join Error:', error);
    }
  });

  socket.on('code-change', async ({ roomId, code, language }) => {
    socket.to(roomId).emit('code-update', { code, language });

    if (inMemoryRooms.has(roomId)) {
      const memRoom = inMemoryRooms.get(roomId);
      memRoom.code = code;
      if (language) memRoom.language = language;
    }

    if (isPgConnected && pool) {
      try {
        await pool.query(
          `INSERT INTO rooms (room_id, code, language, updated_at) 
           VALUES ($1, $2, $3, NOW()) 
           ON CONFLICT (room_id) DO UPDATE SET code = $2, language = $3, updated_at = NOW()`,
          [roomId, code, language || 'javascript']
        );
      } catch (err) {
        // Ignore background DB write error
      }
    }
  });

  socket.on('typing-status', ({ roomId, isTyping }) => {
    socket.to(roomId).emit('user-typing', { socketId: socket.id, isTyping });
  });

  socket.on('save-snapshot', async ({ roomId, code, language }) => {
    try {
      const timestamp = new Date();
      const newSnapshot = { code, language, timestamp };

      if (inMemoryRooms.has(roomId)) {
        const memRoom = inMemoryRooms.get(roomId);
        memRoom.snapshots = memRoom.snapshots || [];
        memRoom.snapshots.push(newSnapshot);
        if (memRoom.snapshots.length > 20) memRoom.snapshots.shift();
        io.in(roomId).emit('snapshot-saved', memRoom.snapshots);
      }

      if (isPgConnected && pool) {
        await pool.query(
          'INSERT INTO snapshots (room_id, code, language, timestamp) VALUES ($1, $2, $3, $4)',
          [roomId, code, language || 'javascript', timestamp]
        );
        // Keep max 20 snapshots per room
        await pool.query(
          `DELETE FROM snapshots WHERE id IN (
            SELECT id FROM snapshots WHERE room_id = $1 ORDER BY timestamp DESC OFFSET 20
          )`,
          [roomId]
        );
        const snapRes = await pool.query(
          'SELECT code, language, timestamp FROM snapshots WHERE room_id = $1 ORDER BY timestamp ASC',
          [roomId]
        );
        io.in(roomId).emit('snapshot-saved', snapRes.rows);
      }
    } catch (err) {
      console.error('Snapshot capture failed:', err);
    }
  });

  socket.on('cursor-move', ({ roomId, position, selection }) => {
    socket.to(roomId).emit('cursor-update', {
      socketId: socket.id,
      position,
      selection
    });
  });

  socket.on('send-message', ({ roomId, message }) => {
    socket.to(roomId).emit('receive-message', message);
  });

  socket.on('disconnecting', () => {
    const userData = userMap.get(socket.id);
    if (userData) {
      const rooms = Array.from(socket.rooms);
      rooms.forEach(roomId => {
        socket.to(roomId).emit('user-left', { socketId: socket.id });
      });
      userMap.delete(socket.id);
    }
  });

  socket.on('disconnect', () => {
    console.log('📡 Node severed:', socket.id);
  });
});

app.get(/(.*)/, (req, res) => {
  res.sendFile(path.join(publicPath, 'index.html'));
});

const PORT = process.env.PORT || 5001;
server.listen(PORT, () => {
  console.log(`🚀 GOAT CORE ACTIVE ON PORT ${PORT}`);
});
